name: Unit Test

on:
  push:
  pull_request:
    types: [synchronize, opened]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Run unit tests
        run: |
          cargo test --verbose

  toml_checks:
    runs-on: ubuntu-latest
    name: Toml check
    steps:
      - uses: actions/checkout@v6
      - name: "Cargo.toml format"
        if: $${{ always() }}
        uses: gwen-lg/taplo-action@v1
        with:
          format: true
          lint: false
      - name: "Cargo.toml lint"
        if: $${{ always() }}
        uses: gwen-lg/taplo-action@v1
        with:
          format: false
          lint: true
